export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';
export const REMOVE_TASK_SUCCESS = 'REMOVE_TASK_SUCCESS';
export const UPDATE_TASK_SUCCESS = 'UPDATE TASK_SUCCESS';
export const LOAD_TASKS_SUCCESS = 'LOAD_TASKS_SUCCESS';
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';